name: Test Python 3.7

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test-py37:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.7'
        cache: 'pip'
    - run: make setup_nightly
    - run: make test

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true
